### ISSUE TITLE
Ball tracking mode

### ISSUE THREAD

**Issue by maxh65000** [Team138Entropy/Entropy2021#19]
- [ ] Utilize a second vision camera (#14 ) to track the yellow balls 
- [ ] Receive packets containing degrees offset on the RIO
- [ ] Turn to the offset via a PID
- [ ] Add autonomous path

This would help the driver in Teleoperated, as well as the driver as we could ensure we are always precisely lined up with our conveyer opening. 

People in the FIRST community have been able to track the ball very well, a lot of this code is open sourced:

https://www.youtube.com/watch?v=Ff9Acvx8gyE&ab_channel=Spectrum3847
